src/js/definitions/models/events/SoloEventBase.js, src/js/pages/view/dashboard/TirednessView.js
E-4 でレア掘り120周やってたら，疲労回復通知が 1分前に来てることに（今さら）気付いたので，修正パッチ作りました．
建造と疲労回復だけ offset 引かないようにしてます．
でぴったりまで待つと，残り時間がまだあるのに「0分」って出るのも妙かなと思って，floor() でなく ceil() 表示にしてみました．
=> 疲労回復通知が 1分前に来るの修正

src/html/settings.html, src/js/definitions/models/MyStorage.js, src/js/pages/proxy2.js, src/js/pages/safe.js, src/js/pages/settings.js, src/js/pages/view/settings/AskBeforeWindowCloseView.js
Apple Magic Mouse の誤爆によるページ遷移に悩む友人提督のために，艦これウィジェットにも「ページ閉じる前に確認」を実装してみました．
onBeforeUnload の中で async に config 取ってくると上手くいかんので，Flash ロードの辺りにコード追加して config 次第でハンドラ仕込むかどうか分けてます．
通常と white で同じコードが！ コピペばんざい！ もっと上手い方法ないんだろーか……
=> add "ask before window close" setting

src/js/Notifier.js
Chrome 47 で，デフォルトで通知が勝手に消えるようになったので，「勝手に消さない」フラグを付けました．
で，自動的に消えるモードの時はどうしようかと思ったけどこれまで通り「勝手に消さないモードの通知を自前 setTimeout で消す）のままにしてます．
あと通知の×ボタン以外をクリックしても消えてくれないので（これはうちの環境だけか？），クリック時に自前で即座に close() するようにしてます．
=> fix Chrome 47 notification issue

src/js/Components/Controllers/RequestControllers/Kousho.js
=> 建造タイマは 1分前行動をしない

src/js/Components/Controllers/MessageControllers/Window.js, src/js/Components/Controllers/NotificationClickControllers/index.js
- 大破進撃防止を別窓設定しているとき
- なおかつ、APPモードでゲームを表示しており、初期のサイズから自分で窓をひっぱってリサイズしているとき
- 別窓表示された大破進撃防止窓をクリックすると、ゲーム画面が *最初にLAUNCHしたサイズ* に回復してしまう
- 右上が使う `/window/open` というコントローラを使いまわしていたことによる
- 右上からのリクエストは必ずframeパラメータがあることを加味し、
- コントローラにおいてframeパラメータが無い場合はresize（回復）を行わないようにした
- 通知クリック時も同様にresize（回復）を行わないようにした
=> 大破進撃防止窓や通知をクリックしたときゲーム画面サイズが回復してしまうバグを修正

src/js/Components/Controllers/ExternalMessageControllers/index.js
外部Chrome拡張と連携済みであるIDの場合は確認ダイアログを表示せずに304(連携済み)を返却
※304はv1準拠
使用想定：通常の場合はダイアログを出さずにチェック終了させ、v1→v2になった等で連携が切れた場合などには確認ダイアログを再度表示するため。
=> 許可済み外部Chrome拡張チェック追加

src/js/Components/Routine/DamageSnapshot.js
=> 大破進撃防止を別窓にしたときマウスオーバーで非表示になってしまうバグを修正

src/js/Application/Routine/DamageSnapshot.js
大破進撃防止窓の窓内表示時に表示箇所を見つけるためのセレクタをひとまず動くよう修正しました．
厳密には `div#flashWrap` の直下の `iframe` が1期の `embed` と等価な気がしますが，一応これで動いているようです．
DecoratePages の `embed#maintenanceswf` と `embed#externalswf` は触っていません．
前者はメンテナンス時でしょうかね，後者はAPPモード用？
=> 第2期のHTMLで大破進撃防止窓の窓内表示が可能となるよう修正

src/js/Applications/Models/Queue/Queue.ts
WebStorm で list() が補完効かないのなんでかなって思って……ｗ
=> Queue._scan() 引数の型を些細に修正

src/js/Applications/Background/Routers/WebRequest.ts
FIX: [連合艦隊で出撃時、道中に通常夜戦マスがあると別窓表示の大破進撃窓が消えずに残る - Google グループ](https://groups.google.com/forum/#!topic/kcwidget/1gEjHEsw1Y0)
=> 連合艦隊マップの通常夜戦マスをサポート

src/js/Applications/Components/Dashboard/ClockView/index.tsx
ダッシュボードの時計の日付の月部分がひと月前になっている(6月なら5月)ので+1した
FYI: [Date.prototype.getMonth() - JavaScript | MDN](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth
=> getMonth()が0始まりなので+1する

src/js/Applications/Background/Controllers/Request/Mission.ts, src/js/Applications/Background/Routers/WebRequest.ts
遠征中止したデータがダッシュボードに残っていたので消すようにした
FYI: https://github.com/otiai10/kanColleWidget/issues/1069
=> 途中で遠征を中止した場合、queueを消す

src/js/Applications/Components/Dashboard/QueuesView/TirednessView.tsx
=> 疲労回復タイマーのバーが 0～14 表示だったのを 1～15 表示になるよう変更

manifest.json, src/js/Applications/Background/Controllers/Message/Capture.ts, src/js/Applications/Background/Controllers/Message/DamageSnapshot.ts, src/js/Applications/Background/Controllers/Request/Shipbuilding.ts, src/js/Applications/Components/Capture/index.tsx, src/js/Applications/Components/DamageSnapshot/index.tsx, src/js/Applications/Components/DeckCapture/index.tsx, src/js/Services/TempStorage.ts, tests/Applications/Background/Controllers/Message/Capture.spec.ts, tests/Services/TempStorage.spec.ts
- 連合艦隊の編成キャプチャをcomposeしてもcaptureが開かない
- localStorageのquota exceeded
- `chrome.storage.local`を使い、`unlimitedStorage`の効果を得る
Fix #1126
=> 連合艦隊の編成キャプチャが生成されない件の修正

src/js/Applications/Context/Features/DamageSnapshot.ts
=> 大破進撃防止窓撮影前の入力不検出ディレイを 8200ms → 8000ms に短縮

src/js/Applications/Context/Features/DamageSnapshot.ts
=> 大破進撃防止窓撮影前の入力不検出ディレイを 8000ms → 7800ms に短縮

src/js/Applications/Components/Options/Frames/index.tsx
fix #1229
button要素の下にあるiconのclickイベントに引っ掛けていたので、buttonの判定に吸われて発火しないことがあったと思われる
=> ゲーム窓サイズ設定の＋ボタンが反応しないことのある不具合の修正

src/js/Applications/Models/Sortie/catalog.ts
海域名はwikiwikiから。
- 1-6 https://wikiwiki.jp/kancolle/%E9%8E%AE%E5%AE%88%E5%BA%9C%E6%B5%B7%E5%9F%9F#area6
- 7-2 https://wikiwiki.jp/kancolle/%E5%8D%97%E8%A5%BF%E6%B5%B7%E5%9F%9F#area2
- 7-3 https://wikiwiki.jp/kancolle/%E5%8D%97%E8%A5%BF%E6%B5%B7%E5%9F%9F#area3
=> 海域名 (1-6, 7-2, 7-3) を追加

src/js/Applications/Components/Popup/OfficialTwitter.tsx
Twitter連携しなおしてください。
アプリ名が「艦これウィジェットのツイッターするやつ**です**」ではなく「艦これウィジェットのツイッターするやつ」に変わってます 😉
=> とりあえず、Twitterでなんかあってもポップアップ開くようにした

src/js/Applications/Context/DMM.ts
運営電文仕様変更に合わせパディング値を修正．
54 → 204 で現状大丈夫そうですがそもそもこの 54 がどこから来てるのかわからなかったので今後の仕様再変更やメッセージ枠サイズ変更でどうなるかは不明です．
変更が繰り返されるようなら設定から調節できるようにしたいですね．
=> 運営電文仕様変更に合わせパディング値を修正
