src/js/pages/mission-info.js

遠征早見表と改修早見表が Wiki の変更に多少なりともついて行きやすくなるかもしれない変更です．

fix mission_info window

---

README.md
manifest/prod.json
src/js/Constants.js
src/js/pages/safe.js

[sync master] 1.5.17

---

src/js/Components/Models/Queue/Queue.js

北号作戦をカタログに追加しました。

---

dest/html/options.html
src/js/Components/Models/Config.js
src/js/Components/Models/index.js
src/js/Components/Views/Options/Settings/Syncs/index.js
src/js/Components/Views/Options/index.js
src/js/entrypoints/global-pollution.js

Related #649
こんな感じをイメージしてます
```js
const sync = new Sync(chrome.storage.sync);
sync.save(["Config", "ScheduledQueues"]);
sync.load(["Config", "ScheduledQueues"], false).then(items => console.log(itmes));
```
cc: @xia-sava

chrome.storage.syncと同期するやつを追加

---

src/js/Components/Views/Options/Settings/ScreenShots/SettingScreenShotFile.js

#655 をひとまず普通に表示されるように改造しました．
なんかズレてる．カッコ悪い．

スクショ拡張子設定に SelectField を使ってみた

---

src/js/Components/Controllers/NotificationClickControllers/index.js
src/js/Components/Routes/NotificationClickRoutes.js

建造と疲労の通知がクリックしても消えないのを修正

---

src/js/Components/Controllers/RequestControllers/Kousho.js
src/js/Components/Controllers/RequestControllers/Sortie.js
src/js/Components/Routes/WebRequestRoutes.js

こぴぺえんじにゃりんぐ……
自分的にここかなーと思ったところで除去するようにしてみましたが，
既存の通知をどのタイミングで除去するかはデザインなので，
とりあえずこれはサジェスト程度のプルリクということでお願いします……

疲労通知が出撃で消える & 建造通知が建造艦獲得で消えるように

---

src/js/Components/Views/Dashboard/Contents/Clock/TirednessRow.js
src/js/entrypoints/global-pollution.js

どうでしょう……？
残り時間表示の方がいいのかしら．あるいは両方？

疲労タイマに終了時刻表示がほしかった

---

dest/html/dsnapshot.html
dest/html/popup.html
src/js/Components/Controllers/RequestControllers/Battle.js
src/js/Components/Controllers/RequestControllers/Port.js
src/js/Components/Models/Config.js
src/js/Components/Models/Queue/Queue.js
src/js/Components/Routine/DamageSnapshot.js
src/js/Components/Services/WindowService/index.js
src/js/Components/Views/DeckCapture/index.js
src/js/Components/Views/Options/Settings/Description.js
src/js/Components/Views/Options/Settings/Syncs/index.js
src/js/Components/Views/Options/Settings/Uncategorized/index.js
src/js/Components/Views/Options/index.js
src/js/entrypoints/pages/dsnapshot.js
webpack.config.js

[WIP] V2/status window outside

---

src/js/Components/Views/Capture/Canvas.js
src/js/Components/Views/Capture/index.js

#658 JPEG肥大化抑止＆ファイルサイズ表示修正

---

src/js/Components/Models/Config.js
src/js/Components/Views/Options/Settings/InApp/index.js
src/js/Components/Views/Options/Settings/Uncategorized/index.js
src/js/Components/Views/Options/index.js
src/js/entrypoints/pages/dmm.js
src/js/entrypoints/pages/osapi.dmm.js

うっかり閉じるボタンを押しちゃったときにアラート出す機能

---

src/js/Components/Controllers/RequestControllers/Kaisou.js
src/js/Components/Controllers/RequestControllers/Kousho.js
src/js/Components/Controllers/RequestControllers/Recovery.js
src/js/Components/Controllers/RequestControllers/Supply.js
src/js/Components/Controllers/RequestControllers/index.js

やったと思うこと
・修復、近代化改修、建造の実装
・補給のファイル分割
やってないこと
・遠征（支援をカウントしない判定の方法が分からないので）
・その他（実装方法自体が分からなかったので）

クロックモード：実績記録の部分的追加

---

src/js/Components/Controllers/RequestControllers/Kousho.js
src/js/Components/Controllers/RequestControllers/Mission.js
src/js/Components/Controllers/RequestControllers/Practice.js
src/js/Components/Controllers/RequestControllers/index.js
src/js/Components/Routes/WebRequestRoutes.js
src/js/Components/Services/KanColleDate/index.js
tests/Components/Services/KanColleDate-test.js

実績記録サボってたやつ全部実装する

---

README.md
package.json
src/js/Components/Services/KanColleDate/index.js
tests/Components/Services/KanColleDate-test.js

Weekly update testcase

---

src/js/Components/Controllers/RequestControllers/Battle.js
src/js/Components/Controllers/RequestControllers/Port.js
src/js/Components/Controllers/RequestControllers/Sortie.js
src/js/Components/Services/SortieContext/index.js
src/js/Components/Views/Options/Settings/InApp/index.js

大破進撃防止窓の最前面固定

---

src/js/Components/Routes/WebRequestRoutes.js

連合艦隊の戦闘時に大破進撃防止窓が閉じないバグの修正

---

src/js/Components/Services/WindowService/index.js

ダッシュボード（クロックモード）のデザインがデフォルトでは崩れていたのの修正

---

src/js/Components/Models/Counter.js
src/js/Components/Views/Dashboard/Contents/Memo/CounterView.js
src/js/Components/Views/Dashboard/Contents/Memo/index.js

カスタムカウンター機能の実装

---

scripts/fetch-wiki-remodels.coffee
src/js/Components/Models/Remodel/catalog.json

catalog.jsonだけでいいので誰かレビューしてください

改修工廠早見表の曜日がバグってたの修正

---

src/js/Components/Controllers/CommandControllers/index.js
src/js/Components/Controllers/MessageControllers/Window.js
src/js/Components/Models/Config.js
src/js/Components/Routine/ResourceRecording.js
src/js/Components/Services/TrimService/index.js
src/js/Components/Views/Capture/index.js
src/js/Components/Views/Options/Settings/ScreenShots/index.js
src/js/Components/Views/Options/Settings/Statistics/index.js
src/js/Components/Views/Options/Settings/Uncategorized/index.js
src/js/Components/Views/Options/index.js
src/js/Components/Views/Statistics/index.js

画像ツイートや画像ダウンロードに関する修正

---

src/js/Components/Routes/WebRequestRoutes.js

夜戦マスで大破進撃窓が消えないバグを解消

---

src/js/Components/Views/Options/Winconfigs/WinconfigView.js

カスタム窓設定の作成後にモード（APP/WHITE）が変えられないバグを修正

---

src/js/Components/Controllers/MessageControllers/Twitter.js
src/js/Components/Models/Resource.js
src/js/Components/Services/Twitter/index.js
src/js/Components/Views/Capture/Dialogs/TweetDialog.js
src/js/Components/Views/Capture/index.js
src/js/Components/Views/Statistics/index.js

ツイート時のタグ付与のUIを改善

---

dest/oauth/chrome_ex_oauth.html
manifest.json
src/js/Components/Services/Twitter/index.js

ディレクトリ直下にあったのをdest/oauth以下に移動しました

oauthCallback用のhtmlの移動

---

src/js/Application/Views/Wiki/RemodelsWiki/index.js

Closes #931 改修工廠早見表の第二番艦カラム幅調整
小さい画面だと若干備考欄の必要装備が見にくいかも

改修工廠早見表の第二番艦カラム幅調整

---

src/js/Application/Models/Remodel/catalog.json

改修工廠データのupdate

---

src/js/Application/Controllers/MessageControllers/Window.js
src/js/Application/Models/Frame.js
src/js/Services/Rectangle/index.js
src/js/Services/Streaming/Recorder/GifRecorder.js
src/js/Services/Streaming/index.js
src/js/Services/TrimService/index.js
src/js/Workers/gif-encoder/worker.js

- [DEFAULT WHITE] 1200 x 720 対応
- [APP] 未対応 (リサイズ問題未修正)

HTML5対応 (DEFAULT WHITE only)

---

src/js/Applications/Context/DMM.ts

リサイズイベントで毎回 Date 呼ぶのもアレかなーと思ったので定番スタイルで記述してみました．

onresize処理を少しだけ軽やかに

---

src/js/Applications/Background/Routers/WebRequest.ts

`api_req_combined_battle/battle` と `api_req_combined_battle/each_battle` を追加しました．

2018初秋イベE3連合艦隊時の大破窓消去トリガを追加

---

src/js/Applications/Context/Features/InAppButtons.ts

FIX: ミュート機能を無効にしてもスクショ機能を使えるようにする

---

src/css/entrypoints/dsnapshot.scss
src/js/Applications/Background/Controllers/Message/Debug.ts
src/js/Applications/Background/Controllers/Request/Recovery.ts
src/js/Applications/Background/Controllers/Request/Shipbuilding.ts
src/js/Applications/Background/Controllers/Request/index.ts
src/js/Applications/Background/Cron/index.ts
src/js/Applications/Background/Routers/WebRequest.ts
src/js/Applications/Background/Routers/WebRequestOnComplete.ts
src/js/Applications/Models/Queue/Recovery.ts
src/js/Applications/Models/Queue/Shipbuilding.ts
src/js/Services/Rectangle.ts
src/js/Services/Window.ts
src/js/definitions/debuggable.d.ts

遠征・修復・建造タイマーの実装

---

src/js/Applications/Background/Routers/WebRequest.ts

E4-2 で見られた `api_req_combined_battle/ec_battle` による戦闘開始を `OnBattleStarted` のトリガとして追加しました．

戦闘開始トリガAPIを追加

---

src/js/Applications/Background/Controllers/Request/Recovery.ts
src/js/Applications/Background/Controllers/Request/Shipbuilding.ts
src/js/Applications/Background/Routers/NotificationClick.ts

変なタイミングで通知が出てた件を暫定対応しました．
あとひとまずクリックで消去できるようにしました．クリックでゲーム画面にフォーカスとかは未対応です．

Fix unexpected notification

---

scripts/deploy.sh

定常リリースっぽいスクリプトのプロトタイプ

---

src/js/Applications/Background/Routers/WebRequest.ts

https://groups.google.com/forum/#!topic/kcwidget/SSQfVMNDM1c

戦闘開始トリガに api_req_battle_midnight/sp_midnight API を追加

---

src/js/Applications/Background/Controllers/Request/Mission.ts
src/js/Applications/Background/Controllers/Request/Recovery.ts
src/js/Applications/Background/Cron/index.ts
src/js/Applications/Components/Options/index.vue
src/js/Applications/Models/Config.ts

Feature notification settings

---

.github/workflows/contrib-notice.yml

issueのclosedでも発火してたので一応openedのフィルタを追加

---

src/js/Applications/Background/Controllers/Request/Shipbuilding.ts
src/js/Applications/Background/Routers/WebRequest.ts

途中で高速建造材使った場合、queueを消す

---

package-lock.json
package.json
src/js/Applications/Background/Controllers/Request/Map.ts
src/js/Applications/Background/Controllers/Request/Quest.ts
src/js/Applications/Background/Routers/WebRequest.ts
src/js/Applications/Models/Quest/catalog.ts
src/js/Applications/Models/Quest/consts.ts
src/js/Applications/Models/Quest/index.ts
src/js/entrypoints/global-pollution.ts
tests/Applications/Background/Controllers/Request/Quest.spec.ts
tests/Applications/Models/Quest.spec.ts

任務着手忘れアラート機能の実装

---

scripts/should_deliver_dev.sh
scripts/version.js
src/js/Applications/Models/Sortie/index.ts
tests/Applications/Background/Controllers/Request/Battle.spec.ts
tests/Applications/Context/DMM.spec.ts

リリースアナウンスの改善とtestの修正

---

src/js/Applications/Components/Capture/index.tsx
src/js/Applications/Components/DeckCapture/index.tsx
src/js/Applications/Models/Settings/ScreenshotSetting.ts
src/js/Services/Window.ts

編成キャプチャからスクショ編集画面への導線を追加

---

src/js/Applications/Components/Dashboard/QuestProgressView/index.tsx
src/js/Applications/Models/Quest/index.ts
tests/Applications/Models/Settings/NotificationSetting.spec.ts
tests/Applications/Models/Settings/ScreenshotSetting.spec.ts

日付依存任務が見えてた問題を修正

---

package.json
src/js/Applications/Background/Controllers/Request/Mission.ts
src/js/Applications/Background/Controllers/Request/Recovery.ts
src/js/Applications/Background/Controllers/Request/Shipbuilding.ts
src/js/Applications/Components/Options/Debugger/Simulator.tsx
src/js/Services/Files/index.ts
src/js/Services/Rectangle/index.js
tests/Applications/Background/Controllers/Request/Map.spec.ts
tests/Applications/Background/Controllers/Request/Mission.spec.ts
tests/Applications/Background/Controllers/Request/Shipbuilding.spec.ts
tests/Applications/Context/Features/InAppButtons.spec.ts
tests/Applications/Models/Settings/NotificationSetting.spec.ts
tests/Services/FileService.spec.ts
tests/Services/NotificationService.spec.ts
tests/Services/TempStorage.spec.ts
tests/setup/filesystem.ts
tests/tools.ts

根性でコードカバレッジ上げた

---

.vscode/settings.json
src/js/Applications/Background/Controllers/Request/Practice.ts
src/js/Applications/Background/Cron/index.ts
src/js/Applications/Background/Routers/WebRequest.ts
tests/Applications/Background/Controllers/Request/Mission.spec.ts
tests/Applications/Background/Controllers/Request/Practice.spec.ts
tests/Applications/Background/Cron/cron.spec.ts
tests/tools.ts

演習準備時に演習任務忘れをアラートする

---

package-lock.json
package.json
src/css/entrypoints/dashboard.scss
src/js/Applications/Background/Controllers/Message/Window.ts
src/js/Applications/Background/Routers/Message.ts
src/js/Applications/Components/Dashboard/ClockView/index.tsx
src/js/Applications/Components/Options/Notifications/index.tsx
tests/Applications/Background/Controllers/Message/Window.spec.ts

Fix #1108 
Related https://github.com/otiai10/chomex/commit/92f294e2fa83c98dac606ddd563454fdebfd32d0

ダッシュボードからスクショ

---

src/js/Applications/Components/Options/Notifications/index.tsx
src/js/Applications/Models/Config.ts
src/js/Applications/Models/Settings/NotificationSetting.ts

疲労回復の通知設定を追加

---

.github/workflows/webstore-prod.yml
.github/workflows/webstore-stage.yml
src/js/Applications/Context/DMM.ts
src/js/Applications/Models/Quest/index.ts
tests/Applications/Context/DMM.spec.ts
tests/Applications/Context/Features/InAppButtons.spec.ts
tests/Applications/Models/Quest.spec.ts
tests/Applications/Models/Settings/NotificationSetting.spec.ts
tests/Services/Rectangle.spec.ts
tests/Services/Window.spec.ts

日付依存のやつ修正とコードカバレッジ改善とリリースのワークフロー調整

---

src/js/Applications/Background/Controllers/Request/Shipbuilding.ts
src/js/Applications/Components/Capture/index.tsx
src/js/Applications/Components/Options/Debugger/DebugModeView.tsx
src/js/Applications/Components/Options/Debugger/index.tsx
src/js/Applications/Models/Settings/DebugSetting.ts
src/js/Services/TempStorage.ts
src/js/Services/Window.ts

OCR画像のデバッグのための設定とViewを作成

---

src/js/Applications/Components/DeckCapture/index.tsx
src/js/Services/ComposeImage/index.ts

編成キャプチャの小さなバグ修正

---

src/js/Applications/Components/DamageSnapshot/index.tsx
src/js/Applications/Components/Dashboard/index.tsx
src/js/Applications/Context/DMM.ts
src/js/Services/Window.ts

Windowsで大破進撃防止窓がだんだん小さくなっちゃう問題の修正

---

manifest.json
package-lock.json
package.json
src/js/Applications/Components/Options/Notifications/index.tsx

未着手任務アラートをオフにできるUIの設置

---

src/js/Applications/Components/Dashboard/ClockView/index.tsx
src/js/Applications/Components/Dashboard/index.tsx

優先度順に上から
1. ユーザー登録のデフォルトアイコンがあればそれを表示
1. ウィンドウが開かれていたらカメラアイコンを表示
1. 開かれていなかったら錨アイコンを表示
#1150

ダッシュボードのアイコンを錨とカメラで切り替える

---

src/js/Applications/Context/Features/InAppButtons.ts

ゲーム画面ミュートボタンの設定反映修正

---

src/js/Applications/Context/Features/InAppButtons.ts

基地航空隊の解除ボタンを押せるようにした

---

.github/workflows/contrib-notice.yml
.github/workflows/webstore-prod.yml

ストアリリース時のアナウンスツイートを修正

---

.github/workflows/egosearch.yml
scripts/egosearch.js

艦これウィジェットちゃんをもっと自動化するやつ

---

.github/workflows/contrib-notice.yml
scripts/egosearch.js

Wikiが更新されたときも艦これウィジェットちゃんに告知してもらう、など

---

CONTRIBUTING.md

forkしたリポジトリでActionsを実行しない方法を記載

---

src/js/Applications/Models/Quest/catalog.ts

デイリー廃棄任務のカテゴリを修正した

---

.github/workflows/javascript-ci.yml
.github/workflows/webstore-stage.yml
manifest.json
package-lock.json
package.json
scripts/create-release-pr.js

1e5135eab6eaeeff998321f20b5d1073abbf9e79 (Hiromu OCHIAI) 明示的にリリースしたいときはmanifest.jsonのバージョンを直接いじればよいと思う
fb871cb2760072f65608c39cfb39cd18d934370e (Hiromu OCHIAI) cutがマルチバイト見てない気がするので適当に-nを追加
fd6a6e17891e0f9c8bfefcf8723bed0b0a52832a (Hiromu OCHIAI) Tweetしたあとのログではid_strを使う
b39439af6c8b0e24bd486de12529bb2c2f73ab89 (Hiromu OCHIAI) issue commentをそのままshellに流したらダメです
a28974f1b6b522a8e96efdf5944188c21f1c419a (Hiromu OCHIAI) ビルドプロセスにTwitterのKeyが渡っていなかった問題を解決
92f23c6492ac4c94bf61f161d86a764fe150802c (Hiromu OCHIAI) 残り時間のバッジ実装
ec8ed051703041c2e3382e0492941c7783449f9e (Hiromu OCHIAI) 編成キャプチャ画面でカスタム設定を削除できるようにした
e7d7ce1b2671e77fd13eb3232b162ddbac94d7fa (Hiromu OCHIAI) メタな通知は２つもいらないので削除
ea25e2064409a81a36aaf319fa3499bc5c0a95ac (Hiromu OCHIAI) 疲労回復タイマーを15分以外も選択できるようにした …

RELEASE: 2020-11-1

---

src/js/Applications/Background/Controllers/Request/Map.ts
src/js/Applications/Background/Routers/WebRequest.ts
src/js/Applications/Models/Sortie/index.ts
tests/Applications/Models/Sortie.spec.ts

6-5海域で1戦目に「2戦目」という表記がされるバグを修正

---

src/js/Applications/Background/Controllers/Request/Battle.ts
src/js/Applications/Models/Sortie/index.ts

6-5の出撃情報コンテキスト（◯戦目）が正しく表示されないバグを修正

---

src/js/Services/OCR/index.ts

This reverts commit 8aae8f1a122b193f5455cf890b460475de433017.
Fix #1296

OCRサーバの巻き戻し

---

.github/FUNDING.yml

GitHub Sponsors のボタンを誰でも追加できるようにした。他にも、Open Collectiveとか追加できますよ。

開発者のみなさん、RepoにFUNDINGボタンを設置したので、自分を追加してください。

---

package-lock.json
package.json

* https://stackoverflow.com/questions/61670459/nodejs-must-use-import-to-load-es-module
* https://github.com/node-fetch/node-fetch#commonjs
* https://github.com/node-fetch/node-fetch/commit/b50fbc105755123cad34fb0bc9d5653ecc693b8a

DO NOT USE node-fetch@3, use @2 instead

---

src/js/Applications/Components/Dashboard/QueuesView/TirednessView.tsx
src/js/Applications/Components/Options/DashboardDesign/index.tsx
src/js/Applications/Models/Settings/TirednessTimerSetting.ts
tests/Applications/Models/Settings/TirednessTimerSetting.spec.ts

疲労タイマークリック時「確認して削除」の他に「黙って削除」の挙動を設定可能にした

---

src/js/Applications/Components/Dashboard/QueuesView/MatrixView.tsx

時間入力モーダルでは Enter 押下で「登録」処理を実行するよう改修

---

src/js/Applications/Background/Controllers/Request/Recovery.ts
src/js/Applications/Background/Controllers/Request/Shipbuilding.ts
src/js/Applications/Components/Options/Debugger/DebugModeView.tsx
src/js/Applications/Models/Settings/DebugSetting.ts
src/js/Services/OCR/index.ts

Add ocr server settings

---

src/js/Applications/Background/Controllers/Request/Recovery.ts
src/js/Applications/Background/Controllers/Request/Shipbuilding.ts
src/js/Applications/Components/Options/Debugger/DebugModeView.tsx
src/js/Applications/Models/Settings/DebugSetting.ts
src/js/Services/OCR/index.ts

DebugSettings の一部に OCR サーバ URL を設定できる機能を実装しました．
デフォルトは空欄で，空の場合は初期設定の（元のままの）URL としています．

OCR サーバを変更出来る機能を実装

---

manifest.json
package-lock.json
package.json
src/js/Applications/Components/Popup/OfficialTwitter.tsx
src/js/Services/API/Twitter.ts

* 2d4e3c8d1325c65c7676d6e73fcb8fd71762f312 TwitterAPIでエラーが出てもpopupが使えるように修正

RELEASE: 3.2.80
